#Whether to dupe mobs ot not and how many extra mobs should spawn mob.
dupe_mobs:
  enabled: true
  count: 9

#Whether to dupe projectiles or not and how many extra of each
dupe_projectiles:
  enabled: true
  count: 9
  #whether to dupe ender pearls or not
  do_ender_pearl: false
  #range of how far a projectile can spawn from the main projectile
  spawn_range: 1.5
  #delay from launching of projectile to the spawning of new ones (in ticks)
  spawn_delay: 10